package bpr.service.backend.managers.events;

public enum Event {
    MQTT_MESSAGE_RECEIVED,
    MQTT_SUBSCRIBE,
    MQTT_PUBLISH,
    MQTT_UNSUBSCRIBE,
    DEVICE_ACTIVATE,
    DEVICE_DEACTIVATE,
    DEVICE_OFFLINE,
    DEVICE_ONLINE,
    DEVICE_INIT_COMM,
    DEVICE_CONNECTED,
    DEVICE_CONNECTED_ERROR,
    TELEMETRY_RECEIVED,
    DEVICE_STATUS_UPDATE,
    CUSTOMER_DETECTED,
    CUSTOMER_IDENTIFIED
}
